version: "3.8"

services:

  tmsys-service:
    build:
      context: ./tmsys-service
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    networks:
      - database_io
      - core_io
      - auth_io

  core-service:
    build:
      context: ./core-service
      dockerfile: Dockerfile
    ports: 
      - 5001:5000
    volumes:
      - ./core:/app
    networks:
      - core_io
      - core_email
      - auth_core
      - kong_core
 
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports: 
      - 5002:5000
    environment:
      AUTH_JWT_KEY: /run/secrets/secret_auth_jwt_key
    secrets:
      - secret_auth_jwt_key
    networks:
      - auth_io
      - auth_core
      - kong_auth

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - database_adminer
      - kong_adminer
  
  kong:
    image: kong:latest
    volumes:
      - ./kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 80:8000
      - 443:8443
    networks:
      - kong_auth
      - kong_core
      - kong_adminer

networks:
  database_adminer:
  database_io:
  core_io:
  core_email:
  auth_core:
  auth_io:
  kong_adminer:
  kong_auth:
  kong_core:



