"""empty message

Revision ID: 9aad57149194
Revises: 
Create Date: 2022-10-05 15:19:19.825692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aad57149194'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_address', sa.String(length=255), nullable=True),
    sa.Column('company_phone', sa.Integer(), nullable=True),
    sa.Column('company_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('driver',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_firstname', sa.String(length=255), nullable=True),
    sa.Column('driver_lastname', sa.String(length=255), nullable=True),
    sa.Column('driver_phone', sa.String(length=50), nullable=True),
    sa.Column('driver_status', sa.Enum('assigned', 'not_assigned', name='driverstatus'), server_default='not_assigned', nullable=False),
    sa.Column('driver_email', sa.String(length=50), nullable=True),
    sa.Column('driver_lat', sa.Float(), nullable=False),
    sa.Column('driver_lng', sa.Float(), nullable=False),
    sa.Column('driver_licence', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', 'driver_lat', 'driver_lng'),
    sa.UniqueConstraint('driver_email'),
    sa.UniqueConstraint('driver_licence'),
    sa.UniqueConstraint('driver_phone'),
    sa.UniqueConstraint('id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_address', sa.String(length=255), nullable=True),
    sa.Column('order_reference', sa.String(length=255), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('order_code', sa.String(length=255), nullable=False),
    sa.Column('order_ht', sa.String(length=255), nullable=True),
    sa.Column('order_tva', sa.String(length=255), nullable=True),
    sa.Column('order_ttc', sa.String(length=255), nullable=True),
    sa.Column('order_status', sa.Enum('CREATED', 'SHIPPING', 'DELIVERD', 'CANCELED', name='orderstatus'), server_default='CREATED', nullable=False),
    sa.Column('order_lat', sa.Float(), nullable=True),
    sa.Column('order_lng', sa.Float(), nullable=True),
    sa.Column('order_time_window', sa.Float(), nullable=True),
    sa.Column('date_received', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('Client', 'Manager', 'Admin', 'Driver', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('truck',
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('truck_name', sa.String(length=255), nullable=True),
    sa.Column('truck_type', sa.Enum('Van', 'Box', 'Trailer', name='trucktype'), nullable=False),
    sa.Column('truck_plate', sa.String(length=255), nullable=True),
    sa.Column('truck_year', sa.String(length=255), nullable=True),
    sa.Column('truck_model', sa.String(length=255), nullable=True),
    sa.Column('truck_capacity', sa.Integer(), nullable=True),
    sa.Column('truck_size', sa.Integer(), nullable=True),
    sa.Column('truck_engine', sa.String(length=255), nullable=True),
    sa.Column('truck_color', sa.String(length=255), nullable=True),
    sa.Column('truck_status', sa.Enum('Available', 'Assigned', name='truckstatus'), server_default='Available', nullable=False),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.PrimaryKeyConstraint('truck_id')
    )
    op.create_table('shipment',
    sa.Column('shipment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipment_seq', sa.String(length=255), nullable=True),
    sa.Column('shipment_status', sa.Enum('READY_TO_SHIP', 'ON_ROUTE', 'LOADING', 'UNLOADING', 'LATE', 'STOPPED', 'NO_CONNECTION', name='shipmentstatus'), server_default='READY_TO_SHIP', nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('shipment_lat', sa.Float(), nullable=True),
    sa.Column('shipment_lng', sa.Float(), nullable=True),
    sa.Column('shipment_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['truck_id'], ['truck.truck_id'], ),
    sa.PrimaryKeyConstraint('shipment_id'),
    sa.UniqueConstraint('shipment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment')
    op.drop_table('truck')
    op.drop_table('user')
    op.drop_table('order')
    op.drop_table('driver')
    op.drop_table('client')
    # ### end Alembic commands ###
